# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f369ea76a935c2047ca9c38455aaa71b5b89108b24aa3505d230b5337b16f35467b8710c2163a5e3dfff3dd6fb50a2637d84cd4cd4077a6a7501baadd30066b

test:
  secret_key_base: c43374d9aa71ef279fccca303c2efc412c46e0de76d14ece3d4db15687267bcd5fe97b5e6543144a256d71032de79eaeddff95658ae67ef9d96cd45c1d2c5100

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
